"""add attempt_count and lease_until to reports

Revision ID: 2075d4bbc353
Revises: cc35ec00da97
Create Date: 2026-09-20 08:13:36.583432

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2075d4bbc353"
down_revision: str | Sequence[str] | None = "cc35ec00da97"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reports",
        sa.Column(
            "attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
    )
    op.add_column(
        "reports", sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reports", "lease_until")
    op.drop_column("reports", "attempt_count")
    # ### end Alembic commands ###
