"""add preferred_domains and report_depth to themes

Revision ID: 58a4a135e3aa
Revises: cc35ec00da97
Create Date: 2026-08-19 08:23:16.814461

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "58a4a135e3aa"
down_revision: str | Sequence[str] | None = "cc35ec00da97"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "themes",
        sa.Column("preferred_domains", sa.ARRAY(sa.String(length=255)), nullable=True),
    )
    op.add_column(
        "themes",
        sa.Column(
            "report_depth",
            sa.Enum(
                "summary",
                "standard",
                "detailed",
                name="ck_themes_report_depth",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
            server_default="standard",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("themes", "report_depth")
    op.drop_column("themes", "preferred_domains")
    # ### end Alembic commands ###
