"""add research usage counter

Revision ID: 7878a31a41d0
Revises: 269c8b809978
Create Date: 2026-09-24 02:46:58.234139

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7878a31a41d0"
down_revision: str | Sequence[str] | None = "269c8b809978"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "research_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "used_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("research_usage")
    # ### end Alembic commands ###
