"""add token usage columns and error_message column to reports

Revision ID: cc35ec00da97
Revises: d46d45862be1
Create Date: 2026-08-17 08:19:59.767957

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc35ec00da97"
down_revision: str | Sequence[str] | None = "d46d45862be1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reports", sa.Column("error_message", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "reports", sa.Column("total_input_tokens", sa.Integer(), nullable=True)
    )
    op.add_column(
        "reports", sa.Column("total_output_tokens", sa.Integer(), nullable=True)
    )
    op.add_column("reports", sa.Column("llm_call_count", sa.Integer(), nullable=True))
    op.drop_constraint(op.f("ck_reports_status"), "reports", type_="check")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    status_values = (
        "ARRAY['pending'::character varying,"
        " 'running'::character varying,"
        " 'completed'::character varying,"
        " 'failed'::character varying]::text[]"
    )
    op.create_check_constraint(
        op.f("ck_reports_status"),
        "reports",
        f"status::text = ANY ({status_values})",
    )
    op.drop_column("reports", "llm_call_count")
    op.drop_column("reports", "total_output_tokens")
    op.drop_column("reports", "total_input_tokens")
    op.drop_column("reports", "error_message")
    # ### end Alembic commands ###
